version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: . #not required in ubuntu vm
    image: 3072001/docker-node-app
    environment:
      - PORT=3000
    command: npm start
